version: '3.3'

services:
  minio1:
    image: minio/minio:RELEASE.2019-09-26T19-42-35Z
    hostname: ministore1
    volumes:
      - minio-guaral-data1:/export1
      - minio-guaral-data2:/export2
      - minio-guaral-data3:/export3
      - minio-guaral-data4:/export4
    ports:
      - "9313:9000"
    networks:
      - minio_distributed_swarm_test
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://ministore1/export{1...4}
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
    #   interval: 30s
    #   timeout: 20s
    #   retries: 3

## By default this config uses default local driver,
## For custom volumes replace with volume driver configuration.
volumes:
  minio-guaral-data1:
  minio-guaral-data2:
  minio-guaral-data3:
  minio-guaral-data4:

networks:
  minio_distributed_swarm_test:
    driver: overlay
