version: '3.3'

services:
  minioguaral1:
    image: i2thub.icesi.edu.co:5000/minio:RELEASE.2019-09-26T19-42-35Z
    hostname: minioguaral1
    volumes:
      - minio-guaral-data1-1:/export1
      - minio-guaral-data1-2:/export2
    ports:
      - "9312:9000"
    networks:
      - proxy
    deploy:
      replicas: 1
      labels: 
        com.df.distribute: "true"
        com.df.notify: "true"
        com.df.port: 9000
#        com.df.reqPathSearchReplace: "/storageminio,/"
        com.df.servicePath: "/minio"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minioguaral{1...2}/export{1...2}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minioguaral2:
    image: i2thub.icesi.edu.co:5000/minio:RELEASE.2019-09-26T19-42-35Z
    hostname: minioguaral2
    volumes:
      - minio-guaral-data2-1:/export1
      - minio-guaral-data2-2:/export2
    ports:
      - "9313:9000"
    networks:
      - proxy
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minioguaral{1...2}/export{1...2}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3


## By default this config uses default local driver,
## For custom volumes replace with volume driver configuration.
volumes:
  minio-guaral-data1-1:
    external: true
  minio-guaral-data1-2:
    external: true
  minio-guaral-data2-1:
    external: true
  minio-guaral-data2-2:
    external: true

networks:
  proxy: 
    external: true
#  net_minio_guaral:
#    driver: overlay

