version: '3.3'

services:
  minio1:
    image: minio/minio:RELEASE.2019-09-26T19-42-35Z
    hostname: minio1
    volumes:
      - data1-1:/data1
      #- data1-1:/export
      - data1-2:/data2
    ports:
      - "9312:9000"
    networks:
      - minio_distributed
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio{1...2}/data{1...2}
    #command: server http://minio{1...2}/export
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio2:
    image: minio/minio:RELEASE.2019-09-26T19-42-35Z
    hostname: minio2
    volumes:
      - data2-1:/data1
      #- data2-1:/export
      - data2-2:/data2
    ports:
      - "9313:9000"
    networks:
      - minio_distributed
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio{1...2}/data{1...2}
    #command: server http://minio{1...2}/export
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3


## By default this config uses default local driver,
## For custom volumes replace with volume driver configuration.
volumes:
  data1-1:
  data1-2:
  data2-1:
  data2-2:

networks:
  minio_distributed:
    driver: overlay
